name: my_environment
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - accelerate
  - datasets
  - peft
  - wandb
  - omegaconf
  - s3fs
  - smart_open
  - Pillow
  - cudatoolkit=11.8

  # pip section for additional packages
  - pip:
      - pymupdf
      - pypdf
      - pypdfium2
      - transformers @ git+https://github.com/huggingface/transformers.git@f9b44097261270377199bb0fcbceb01fd9f7d0c0
      - lingua-language-detector
      - necessary
      - cached-path

      # CUDA PyTorch package with index URL
      - --index-url https://download.pytorch.org/whl/cu118
      - torch
      - torchvision
